-- 1CRYPTEN SPACE V4.0 - Supabase Schema

-- Table: banca_status
CREATE TABLE IF NOT EXISTS banca_status (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    saldo_total FLOAT DEFAULT 0,
    risco_real_percent FLOAT DEFAULT 0,
    slots_disponiveis INT DEFAULT 10,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table: slots_ativos
CREATE TYPE risk_status AS ENUM ('ATIVO', 'RISCO_ZERO');

CREATE TABLE IF NOT EXISTS slots_ativos (
    id INT PRIMARY KEY, -- 1 to 10
    symbol TEXT,
    side TEXT,
    entry_price FLOAT,
    current_stop FLOAT,
    status_risco risk_status DEFAULT 'ATIVO',
    pnl_percent FLOAT DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table: journey_signals
CREATE TABLE IF NOT EXISTS journey_signals (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    symbol TEXT,
    indicators JSONB,
    score INT,
    outcome BOOLEAN,
    is_elite BOOLEAN DEFAULT FALSE
);

-- Table: orders
CREATE TABLE IF NOT EXISTS orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    bybit_order_id TEXT UNIQUE,
    symbol TEXT,
    side TEXT,
    qty FLOAT,
    entry_price FLOAT,
    stop_loss FLOAT,
    take_profit FLOAT,
    status TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table: system_logs
CREATE TABLE IF NOT EXISTS system_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    agent TEXT NOT NULL,
    message TEXT NOT NULL,
    level TEXT DEFAULT 'INFO'
);

-- Enable Realtime for these tables
ALTER PUBLICATION supabase_realtime ADD TABLE banca_status;
ALTER PUBLICATION supabase_realtime ADD TABLE slots_ativos;
ALTER PUBLICATION supabase_realtime ADD TABLE journey_signals;
ALTER PUBLICATION supabase_realtime ADD TABLE orders;
ALTER PUBLICATION supabase_realtime ADD TABLE system_logs;

-- Initial data for banca_status
INSERT INTO banca_status (saldo_total, risco_real_percent, slots_disponiveis) 
VALUES (0, 0, 10);

-- Initial rows for slots (placeholder slots 1-10)
DO $$
BEGIN
    FOR i IN 1..10 LOOP
        INSERT INTO slots_ativos (id, symbol, status_risco) VALUES (i, NULL, 'ATIVO');
    END LOOP;
END $$;
